BITMEX_EXCHANGE_ID = 'bitmex'
BINANCE_EXCHANGE_ID = 'binance'
# CURRENCY_SYMBOL = "BTC/USD"
CURRENCY_SYMBOL = "BTC/USDT"
INDICATOR_CANDLE_DURATION = 5
INDICATOR_FRAME_COUNT = 20

CANDLE_TIMESTAMP_INDEX = 0
CANDLE_OPEN_PRICE_INDEX = 1
CANDLE_HIGHEST_PRICE_INDEX = 2
CANDLE_LOWEST_PRICE_INDEX = 3
CANDLE_CLOSING_PRICE_INDEX = 4
CANDLE_VOLUME_INDEX = 5

ALGORITHM_CONFIGURATION_SYSTEM_ID_INDEX = 0
ALGORITHM_CONFIGURATION_ALGORITHM_ID_INDEX = 1
ALGORITHM_CONFIGURATION_SYSTEM_STATE_INDEX = 2

# Bollinger Band specific configurations
BB_STANDARD_DEVIATION = 2.2

# RSI Band specific configurations
RSI_UPPER_BAND_INTENSITY = 70
RSI_LOWER_BAND_INTENSITY = 30

# Funding time related variables
MARKET_HALT_SECONDS_TO_FUNDING = 3600
MARKET_DEAD_STOP_SECONDS_TO_FUNDING = 900

FIRST_FUNDING_HOUR = 4
SECOND_FUNDING_HOUR = 12
THIRD_FUNDING_HOUR = 20

# Trading related constants
ALGORITHM_EXPOSURE = 0.9

