BITMEX_EXCHANGE_ID = 'bitmex'
BINANCE_EXCHANGE_ID = 'binance'
CANDLE_TIMESTAMP_INDEX = 0
CANDLE_OPEN_PRICE_INDEX = 1
CANDLE_HIGHEST_PRICE_INDEX = 2
CANDLE_LOWEST_PRICE_INDEX = 3
CANDLE_CLOSING_PRICE_INDEX = 4
CANDLE_VOLUME_INDEX = 5

ALGORITHM_CONFIGURATION_ID_INDEX = 0
ALGORITHM_CONFIGURATION_TRADING_STATE_INDEX = 1
ALGORITHM_CONFIGURATION_ALGORITHM_NAME_INDEX = 4
ALGORITHM_CONFIGURATION_EXCHANGE_NAME_INDEX = 9
ALGORITHM_CONFIGURATION_API_KEY_INDEX = 10
ALGORITHM_CONFIGURATION_API_SECRET_INDEX = 11
ALGORITHM_CONFIGURATION_TRADING_PAIR_SYMBOL_INDEX = 12
ALGORITHM_CONFIGURATION_INDICATOR_CANDLE_DURATION_INDEX = 13
ALGORITHM_CONFIGURATION_INDICATOR_FRAME_COUNT_INDEX = 14
ALGORITHM_CONFIGURATION_BB_STANDARD_DEVIATION_INDEX = 15
ALGORITHM_CONFIGURATION_RSI_UPPER_INTENSITY_INDEX = 16
ALGORITHM_CONFIGURATION_RSI_LOWER_INTENSITY_INDEX = 17
ALGORITHM_CONFIGURATION_EXPOSURE_INDEX = 18
ALGORITHM_CONFIGURATION_EMA_SMOOTHING_FACTOR_INDEX = 19
ALGORITHM_CONFIGURATION_STARTING_MINUTE_MULTIPLE_INDEX = 20
ALGORITHM_CONFIGURATION_STANDARD_DEVIATION_INDEX = 21

# Funding time related variables
MARKET_HALT_SECONDS_TO_FUNDING = 3600
MARKET_DEAD_STOP_SECONDS_TO_FUNDING = 900

FIRST_FUNDING_HOUR = 4
SECOND_FUNDING_HOUR = 12
THIRD_FUNDING_HOUR = 20

# Algorithm name related variables
EMA_21_ANALYSER_BASE_VERSION = 'e_m_a_21_analyser'

BB_RSI_ANALYSER_BASE_VERSION = 'bb_rsi_analyser'
BB_RSI_ANALYSER_15_MINUTE_CANDLES = 'bb_rsi_analyser_15_min'
BB_RSI_ANALYSER_15_MINUTE_CANDLES_IMPROVED = 'bb_rsi_analyser_15_min_improved'
BB_RSI_ANALYSER_V3 = 'bb_rsi_analyser_v3'

PRICE_DATA_GENERATION_BASE_VERSION = 'price_data_generation'
